#
# Use this configuration file to control what RobotPy packages are installed on your RoboRIO
# Note: use provided conda environment via `conda env create -f WPILib-Python-Test.yaml`
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2024.1.1.3"

# Which extra RobotPy components should be installed -> equivalent to `pip install robotpy[extra1, ...]
robotpy_extras = [
    "navx",
    "rev",
    "ctre"
]

# Other pip packages to install
requires = [ "numpy" ]